### ISSUE TITLE
cur(sor) and deleteResult gets nil pointer

### ISSUE THREAD

**Issue by axcosta** [tfogo/mongodb-go-tutorial#2]
Just a heads up as when executing finding multiple documents and deleting all documents, cursor and deleteResult gets nil pointer when filter is set to nil. If filter is set to `bson.D{{}}`, then all goes well.

**Comment by tfogo** [comment]
Thanks @axcosta! 

In version 0.1.0 of the driver, you could pass `nil` as a filter document. I have updated the code so that it's compatible with later versions of the driver that require `bson.D{{}}` instead.
